apiVersion: v1
kind: ConfigMap
metadata:
  name: casc-oc
data:
  bundle.yaml: |
    apiVersion: "1"
    id: "jenkins"
    description: "OC Bundle"
    version: "35"
    plugins:
      - "plugins.yaml"
    jcasc:
      - "jenkins.yaml"
    rbac:
      - "rbac.yaml"
    items:
      - "items.yaml"
  jenkins.yaml: |
    jenkins:
      agentProtocols:
      - "Diagnostic-Ping"
      - "JNLP4-connect"
      - "OperationsCenter2"
      - "Ping"
      authorizationStrategy: "cloudBeesRoleBasedAccessControl"
      crumbIssuer:
        standard:
          excludeClientIPFromCrumb: true
      disableRememberMe: true
      labelAtoms:
      - name: "master"
      markupFormatter: "plainText"
      mode: NORMAL
      myViewsTabBar: "standard"
      numExecutors: 2
      primaryView:
        masters:
          columns:
          - "jobName"
          - "status"
          - "weather"
          - "masterConfigurationStaleViewColumn"
          - "jenkinsVersionViewColumn"
          - "cascViewColumn"
          - "manageMaster"
          - "totalJobsViewColumn"
          - "queueSizeViewColumn"
          - "listSelectionColumn"
          jobFilters:
          - "connectedMasterViewFilter"
          name: "Controllers"
          recurse: true
      projectNamingStrategy: "standard"
      quietPeriod: 5
      remotingSecurity:
        enabled: true
      scmCheckoutRetryCount: 0
      securityRealm:
        ldap:
          configurations:
          - displayNameAttributeName: "cn"
            groupMembershipStrategy:
              fromGroupSearch:
                filter: "member={0}"
            groupSearchBase: "ou=Groups"
            inhibitInferRootDN: false
            managerDN: "cn=admin,dc=example,dc=org"
            managerPasswordSecret: NotARealPasswordObviously
            rootDN: "dc=example,dc=org"
            server: "ldap://ldap-openldap:389"
            userSearchBase: "ou=People"
          disableMailAddressResolver: false
          groupIdStrategy: "caseInsensitive"
          userIdStrategy: "caseInsensitive"        
      slaveAgentPort: 50000
      views:
      - masters:
          columns:
          - "jobName"
          - "status"
          - "weather"
          - "masterConfigurationStaleViewColumn"
          - "jenkinsVersionViewColumn"
          - "cascViewColumn"
          - "manageMaster"
          - "totalJobsViewColumn"
          - "queueSizeViewColumn"
          - "listSelectionColumn"
          jobFilters:
          - "connectedMasterViewFilter"
          name: "Controllers"
          recurse: true 
      - all:
          name: "all"  
      viewsTabBar: "standard"          
    cloudBeesCasCServer:
      defaultBundle: "mc1"
      visibility: true
    beekeeper:
      enabled: true
      securityWarnings:
        enabledForCore: true
        enabledForPlugins: true
      upgrades:
        autoDowngradePlugins: false
        autoUpgradePlugins: true
    notificationConfiguration:
      enabled: false

    masterprovisioning:
      dockerImageDefinitionConfiguration:
        images:
        - imageTag: "cloudbees/cloudbees-core-mm:2.303.2.5"
          name: "CloudBees CI - Managed Master - 2.303.2.5"
        - imageTag: "cloudbees/cloudbees-core-mm:2.303.2.3"
          name: "CloudBees CI - Managed Master - 2.303.2.3"
        - imageTag: "cloudbees/cloudbees-core-mm:2.303.1.6"
          name: "CloudBees CI - Managed Master - 2.303.1.6"
        - imageTag: "cloudbees/cloudbees-core-mm:2.289.3.2"
          name: "CloudBees CI - Managed Master - 2.289.3.2" 
      kubernetes:
        clusterEndpoints:
        - id: "default"
          ingressClass: "nginx"
          jenkinsUrl: "http://cjoc.cbci.svc.cluster.local/cjoc/"
          name: "kubernetes"
        cpus: "1.0"
        disk: 50
        fsGroup: "1000"
        globalJavaOptions: "-Djenkins.model.Jenkins.crumbIssuerProxyCompatibility=true\
          \ -Dorg.csanchez.jenkins.plugins.kubernetes.pipeline.PodTemplateStepExecution.defaultImage=cloudbees/cloudbees-core-agent:2.303.2.5\
          \ -Dcom.cloudbees.jenkins.plugins.kube.ServiceAccountFilter.defaultServiceAccount=jenkins-agents\
          \ -Dcom.cloudbees.networking.useSubdomain=false -Dcom.cloudbees.networking.protocol=\"\
          https\" -Dcom.cloudbees.networking.hostname=\"ci.pmgke.kearos.net\" -Dcom.cloudbees.networking.port=443\
          \ -Dcom.cloudbees.networking.operationsCenterName=\"cjoc\""
        javaOptions: "-XshowSettings:vm -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+DisableExplicitGC\
          \ -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -Dhudson.slaves.NodeProvisioner.initialDelay=0"
        livenessInitialDelaySeconds: 300
        livenessPeriodSeconds: 12
        livenessTimeoutSeconds: 12
        memory: 3072
        readinessFailureThreshold: 100
        readinessInitialDelaySeconds: 30
        readinessTimeoutSeconds: 5
        terminationGracePeriodSeconds: 1200
        yaml: |-
          apiVersion: "apps/v1"
          kind: "StatefulSet"
          spec:
            template:
              metadata:
                annotations:
                  prometheus.io/path: /${name}/prometheus
                  prometheus.io/port: "8080"
                  prometheus.io/scrape: "true"
                labels:
                  app.kubernetes.io/component: Managed-Master
                  app.kubernetes.io/instance: ${name}
                  app.kubernetes.io/managed-by: CloudBees-Core-Cloud-Operations-Center
                  app.kubernetes.io/name: ${name}        
    security:
      anonymizeSupportBundle:
        enabled: false
      apiToken:
        creationOfLegacyTokenEnabled: false
        tokenGenerationOnCreationEnabled: false
        usageStatisticsEnabled: true
      sSHD:
        port: -1
      securitySettingsEnforcement:
        global:
          realmAndAuthorization:
            canCustomMapping: false
            canOverride: false
            defaultMappingFactory: "restrictedEquivalentRAMF"
    unclassified:
      buildDiscarders:
        configuredBuildDiscarders:
        - "jobBuildDiscarder"
      cloudbeesPrometheus:
        collectingMetricsPeriodInSeconds: 30
        defaultNamespace: "cb_ci"
        path: "prometheus"
        useAuthenticatedEndpoint: false
      experimentalPlugins:
        enabled: false
  items.yaml: |
    removeStrategy:
      rbac: SYNC
      items: NONE
    items:
    - kind: "freeStyle"
      name: "casc-sync"
      displayName: "CasC Bundle Sync"
      description: "Syncronizes CasC Bundles."
      disabled: false
      quietPeriod: 10
      scm:
        gitSCM:
          gitTool: git
          userRemoteConfigs:
            - userRemoteConfig:
                url: "https://github.com/joostvdg/jenkins-examples.git"
      builders:
        - shell:
            command: "cp -R casc/* ${JENKINS_HOME}/jcasc-bundles-store"      
    - kind: folder
      name: casc
      description: ''
    - kind: folder
      name: myfolder
      description: ''
    - kind: folder
      name: myotherfolder
      description: ''
    - kind: folder
      name: Teams  
    - kind: managedController
      displayName: 'Blue'
      name: mc-blue
      description: 'Blue Controller (Managed)'
      groups:
      - members:
          users:
          - bluedev
          - blueadmin
        name: Blues
      properties:
      - configurationAsCode:
          bundle: mc21
      - healthReporting:
          enabled: true
      - licensing:
          strategy:
            perUserLicensingStrategy: {}
      configuration:
        kubernetes:
          memory: 3072
          cpus: 1.0
          disk: 50
          domain: blue
          yaml: ''
    - kind: managedController
      displayName: 'Green'
      name: mc-green
      description: 'Green Controller (Managed)'
      groups:
      - members:
          users:
          - greendev
          - greenadmin
        name: Greens
      properties:
      - configurationAsCode:
          bundle: mc1
      - healthReporting:
          enabled: true
      - licensing:
          strategy:
            perUserLicensingStrategy: {}
      configuration:
        kubernetes:
          memory: 3072
          cpus: 1.0
          disk: 50
          domain: green
          yaml: ''


  rbac.yaml: |
    removeStrategy:
      rbac: SYNC
    roles:
    - name: authenticated
    - permissions:
      - hudson.model.Hudson.Administer
      name: administer
    - name: anonymous
    - filterable: 'true'
      permissions:
      - hudson.model.Item.Cancel
      - hudson.model.Item.Build
      - hudson.model.Item.Move
      - hudson.model.Item.Create
      - hudson.model.View.Create
      - hudson.model.Run.Update
      - hudson.model.View.Delete
      - hudson.model.Run.Delete
      - hudson.model.View.Configure
      - hudson.model.Item.Promote
      - hudson.model.Item.Configure
      - hudson.model.Item.Read
      - hudson.scm.SCM.Tag
      - hudson.model.Item.Discover
      - hudson.model.Hudson.Read
      - hudson.model.Item.Workspace
      - hudson.model.View.Read
      - hudson.model.Item.Delete
      - hudson.model.Item.Request
      name: develop
    - filterable: 'true'
      permissions:
      - hudson.model.Item.Read
      - hudson.model.Item.Discover
      - hudson.model.Hudson.Read
      - hudson.model.View.Read
      name: browse
    groups:
    - members:
        external_groups:
          - Administrators
        users:
        - admin
      roles:
      - name: administer
        grantedAt: current
      name: Administrators
    - roles:
      - name: develop
        grantedAt: current
      name: Developers
      members:
        external_groups:
          - BlueAdmins
          - GreenAdmins
    - roles:
      - name: browse
        grantedAt: current
      name: Browsers
      members:
        external_groups:
          - Blue
          - Green
  plugins.yaml: |
    plugins:
    - {id: ace-editor}
    - {id: antisamy-markup-formatter}
    - {id: apache-httpcomponents-client-4-api}
    - {id: async-http-client}
    - {id: authentication-tokens}
    - {id: aws-credentials}
    - {id: aws-java-sdk}
    - {id: blueocean-commons}
    - {id: blueocean-rest}
    - {id: bluesteel-cjoc}
    - {id: bootstrap4-api}
    - {id: bouncycastle-api}
    - {id: caffeine-api}
    - {id: checks-api}
    - {id: cloudbees-administrative-monitors}
    - {id: cloudbees-analytics}
    - {id: cloudbees-assurance}
    - {id: cloudbees-blueocean-default-theme}
    - {id: cloudbees-casc-api}
    - {id: cloudbees-casc-server}
    - {id: cloudbees-folder}
    - {id: cloudbees-folders-plus}
    - {id: cloudbees-jenkins-advisor}
    - {id: cloudbees-license}
    - {id: cloudbees-monitoring}
    - {id: cloudbees-platform-common}
    - {id: cloudbees-platform-data}
    - {id: cloudbees-plugin-usage}
    - {id: cloudbees-ssh-slaves}
    - {id: cloudbees-support}
    - {id: cloudbees-uc-data-api}
    - {id: cloudbees-unified-ui}
    - {id: cloudbees-update-center-plugin}
    - {id: command-launcher}
    - {id: configuration-as-code}
    - {id: credentials}
    - {id: credentials-binding}
    - {id: display-url-api}
    - {id: docker-commons}
    - {id: durable-task}
    - {id: echarts-api}
    - {id: font-awesome-api}
    - {id: git}
    - {id: git-client}
    - {id: handy-uri-templates-2-api}
    - {id: infradna-backup}
    - {id: jackson2-api}
    - {id: jaxb}
    - {id: jdk-tool}
    - {id: jjwt-api}
    - {id: jquery3-api}
    - {id: jsch}
    - {id: junit}
    - {id: kube-agent-management}
    - {id: kubernetes}
    - {id: kubernetes-client-api}
    - {id: kubernetes-credentials}
    - {id: ldap}
    - {id: mailer}
    - {id: mapdb-api}
    - {id: master-provisioning-core}
    - {id: master-provisioning-kubernetes}
    - {id: metrics}
    - {id: nectar-license}
    - {id: nectar-rbac}
    - {id: node-iterator-api}
    - {id: oauth-credentials}
    - {id: okhttp-api}
    - {id: operations-center-agent}
    - {id: operations-center-clusterops}
    - {id: operations-center-context}
    - {id: operations-center-elasticsearch-provider}
    - {id: operations-center-jnlp-controller}
    - {id: operations-center-kubernetes-cloud}
    - {id: operations-center-license}
    - {id: operations-center-monitoring}
    - {id: operations-center-rbac}
    - {id: operations-center-server}
    - {id: operations-center-sso}
    - {id: operations-center-updatecenter}
    - {id: plain-credentials}
    - {id: plugin-util-api}
    - {id: popper-api}
    - {id: pubsub-light}
    - {id: scm-api}
    - {id: script-security}
    - {id: snakeyaml-api}
    - {id: sse-gateway}
    - {id: ssh-credentials}
    - {id: sshd}
    - {id: structs}
    - {id: support-core}
    - {id: token-macro}
    - {id: trilead-api}
    - {id: unique-id}
    - {id: user-activity-monitoring}
    - {id: variant}
    - {id: view-job-filters}
    - {id: workflow-api}
    - {id: workflow-scm-step}
    - {id: workflow-step-api}
    - {id: workflow-support}
    - {id: cloudbees-prometheus}
    - {id: wikitext}
    - {id: external-notification}
    - {id: notification-api}
    - {id: operations-center-notification}
    - {id: saml}



