OperationsCenter:
  HostName: ci.example.com
  CSRF:
    ProxyCompatibility: true
  Annotations:
    prometheus.io/path: "/prometheus"
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  Ingress:
    Annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: 'true'
      kubernetes.io/ingress.class: nginx
    tls:
      Enable: true
      Host: ci.example.com
      SecretName: tls-ci-example-com
  JavaOpts:
    -Djenkins.install.runSetupWizard=false
    -Dcore.casc.config.bundle=/var/jenkins_config/oc-casc-bundle
  ExtraVolumes:
  - name: casc-oc-volume
    configMap:
      name: casc-oc
  ExtraVolumeMounts:
  - name: casc-oc-volume
    mountPath: /var/jenkins_config/oc-casc-bundle
    readOnly: true

Agents:
  Enabled: true
  SeparateNamespace:
    Enabled: true
    Name: ci-agents
    Create: true

Hibernation:
  Enabled: true
